version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - backend/.env

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"

  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
